server:
  # ???
  port: 8082

spring:
  application:
    name: rate
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      password: redis
      connect-timeout: 10s
      ssl:
        enabled: false

redisson:
  # redis key前缀
  keyPrefix:
  # 线程池数量
  threads: 4
  # netty连接池数量
  nettyThreads: 8
  # 单节点配置
  singleServerConfig:
    clientName: aaa
    # 连接池最小空闲数
    connectionMinimumIdleSize: 8
    # 连接池大小
    connectionPoolSize: 32
    # 空闲超时，单位毫秒
    idleConnectionTimeout: 10000
    # 命令等待超时，单位毫秒
    timeout: 3000
    # 发布和订阅连接池大小
    subscriptConnectionPoolSize: 50
