server:
  # ???
  port: 8082

spring:
  application:
    name: rate
  data:
    redis:
      # ??
      host: 127.0.0.1
      # ??
      port: 6379
      # ?????
      database: 1
      # ?? ??????????????
      # password:
      # ??????
      connect-timeout: 10s
      # ????ssl
      ssl:
        enabled: false

redisson:
  # redis key??
  keyPrefix:
  # ?????
  threads: 4
  # netty?????
  nettyThreads: 8
  # ?????
  singleServerConfig:
    clientName: aaa
    # ????????
    connectionMinimumIdleSize: 8
    # ?????
    connectionPoolSize: 32
    # ?????????
    idleConnectionTimeout: 10000
    # ???????????
    timeout: 3000
    # ??????????
    subscriptConnectionPoolSize: 50
