# 配置从Nacos读取
#server:
#  #  ${port:8083} 没有port参数，使用8083端口，有port参数则使用port参数指定的端口，使用8084端口的支付服务。 -Dport=8084
#  port: ${port:8083}

# 配置从Nacos common.yaml读取
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848 #配置Nacos地址
#        # 服务注册到哪个命名空间下，不配置namespace默认为public
#        namespace: 5f519613-5347-4d9e-845c-89ca31271b99

# Sleuth 链路追踪时，需要设置此日志级别，否则不打印span Id
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG