server:
  port: 8050

# zuul的注册地址
eureka:
  client:
    serviceUrl:
      defaultZone:  http://admin:password@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: zuul

zuul:
  host:
    socket-timeout-millis: 180000
    connect-timeout-millis: 180000
  routes:
    EUREKA-SERVICE:
      path: /service/**
      sensitiveHeaders: