server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名称
  client:
    #false 表示不向注册中心注册自己。
    register-with-eureka: false
    #false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    serviceUrl:
      #集群版 将当前的 Eureka Server 注册到 7002 和 7003 上，形成一组互相注册的 Eureka Server 集群
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

  server:
    # 关闭 Eureka 的自我保护机制，默认是开启,一般不建议大家修改
    # enable-self-preservation: false