server:
  port: 8001

spring:
  application:
    name: eureka-provider

eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
      # 这个地址是 eureka-server注册中心在 application.yml 中暴露出来额注册地址 （单机版）
      defaultZone: http://localhost:8761/eureka
      # 将服务注册到 Eureka Server 集群
      # defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: eureka-provider #自定义服务名称信息
    prefer-ip-address: true  #显示访问路径的 ip 地址